#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Android.ExtendedControls.Resource", IsApplication=true)]

namespace Android.ExtendedControls
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int radio_colors = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int segment_grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int segment_grey_focus = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int segment_grey_press = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int segment_radio_grey_left = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int segment_radio_grey_left_focus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int segment_radio_grey_left_press = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int segment_radio_grey_middle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int segment_radio_grey_middle_focus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int segment_radio_grey_middle_press = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int segment_radio_grey_right = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int segment_radio_grey_right_focus = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int segment_radio_grey_right_press = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int segment_radio_white_left = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int segment_radio_white_left_focus = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int segment_radio_white_left_press = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int segment_radio_white_middle = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int segment_radio_white_middle_focus = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int segment_radio_white_middle_press = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int segment_radio_white_right = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int segment_radio_white_right_focus = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int segment_radio_white_right_press = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int segment_white = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int segment_white_focus = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int SegmentButton = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int SegmentRadioLeft = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int SegmentRadioMiddle = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int SegmentRadioRight = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
